### ISSUE TITLE
terrible performance of SetXXX methods

### ISSUE THREAD

**Issue by zhaoguojie2010** [zombiezen/go-capnproto2#44] opened 2016-08-02 11:30 UTC
#My capnp file is as follow:
```
struct Request {
    sourceID @0         :Text;
    reportID @1         :Text;
    reportVersion @2    :Int32;
    klen @3             :Int32;
    key @4              :Text;
    data @5             :Data;
}

struct Requests {
    id @0       :Text;
    count @1    :UInt32;
    reqs @2      :List(Request);
}

```

I have a Batcher struct that batches multiple Request into one Requests.
```
type Batcher struct {
    // ... some fields
    // capnp structs
    msg     *capnp.Message
    seg     *capnp.Segment
    reqList capnpmsg.Request_List

    // ... some other fields
}
```

Now we initialize the Batcher with this method
```
func (this *Batcher) prepare() (err error) {
    if this.msg, this.seg, err = capnp.NewMessage(capnp.SingleSegment(nil)); err != nil {
        return err
    }
    if r, err := capnpmsg.NewRootRequests(this.seg); err != nil {
        return err
    } else {
        if this.reqList, err = r.NewReqs(int32(this.capacity)); err != nil {
            return err
        }
        // some Ops...
    }
    return err
}
```

Now start batching Request
```
func (this *Batcher) Batch(sid string, rid string, rv int, klen int, key string, types []string, values []interface{}) error {
    // some code....
    req, err := capnpmsg.NewRequest(this.seg)
    if err != nil {
        return err
    }
    req.SetSourceID(sid)
    req.SetReportID(rid)
    req.SetReportVersion(int32(rv))
    req.SetKlen(int32(klen))
    req.SetKey(key)
    req.SetData(buff)
    if err := this.reqList.Set(int(this.curSize), req); err != nil {
        return err
    }
    // some code...
    return nil
}
```

the profiling result is as follow:
<img width="1388" alt="profiling_capnp" src="https://cloud.githubusercontent.com/assets/9110129/17326843/a060d9e4-58e6-11e6-895c-0b09256986ea.png">

As you can see, **[SetSourceID SetReportID  SetKey  SetData]** take about 70% of the Batch's running time. Am i not using the api right? How to improve the performance? Thanks!!

**Comment by zombiezen** [comment] 2016-08-02 15:31
Two things:

1. I would expect those setter methods to be a large percentage of the running time of Batch: after all, that's a vast majority of what that function does.  I would like to see the profile below those setters: it's hard for me to debug/explain what you're seeing without seeing where the time is being spent in those setters.
2. You are making more allocations than necessary: when you call `Requests.NewReqs` above, it already allocates the space for all of the `Request` structs.  Using `Request_List.Set` will necessarily copy the data and pointers.  I suspect that's the actual bottleneck of your application.

Please give me the profile data for (1) before making the change I suggest in (2).

**Comment by zhaoguojie2010** [comment] 2016-08-03 09:03
Hello, thanks for the help.
profile data is as follow:
<img width="1753" alt="capnp_profiling" src="https://cloud.githubusercontent.com/assets/9110129/17353857/7c523f3a-5976-11e6-97a8-56ded0523eab.png">


Also I made some change as you mentioned earlier.
```
func (this *Batcher) Batch(sid string, rid string, rv int, klen int, key string, types []string, values []interface{}) error {
    // some code ...
    // remove req, err := capnpmsg.NewRequest(this.seg) from the earlier version, instead use
    // Request_List.At() get the pre-allocated request, then call the setters.
    req := this.reqList.At(int(this.curSize))
    req.SetSourceID(sid)
    req.SetReportID(rid)
    req.SetReportVersion(int32(rv))
    req.SetKlen(int32(klen))
    req.SetKey(key)
    req.SetData(buff)
    // some code ...
    return nil
}
```

well, this doesn't help, the profiling result is as follow:
<img width="1335" alt="capnp-profiling-2" src="https://cloud.githubusercontent.com/assets/9110129/17359363/cec70242-5998-11e6-89c0-430b02374de2.png">

One thing worth noticing is that `SetReportID` doesn't take any cpu time this time, which is quite weird.

so now we are sure that the bottleneck is `singleSegmentArena.Allocate(...)`. Is there any thing we could do about that(maybe mempool)?

**Comment by zombiezen** [comment] 2016-08-03 17:01
Okay, this makes much more sense to me.  I somehow thought the fields were mostly ints, not strings/blobs.

`singleSegmentArena.Allocate` is already fairly fast. It sounds like you're creating messages that are quite large, which is &mdash; by design &mdash; not what single segment arenas are good for: they start off at 4KiB, then grow as necessary.  However, this growing requires copying the data from the smaller buffers, which is slow (the `memmove` you saw).  So you can do one of two things: either increase the capacity of your arena upfront (`capnp.SingleSegment(make([]byte, 0, 16<<10))`) or use `capnp.MultiSegment`, which will just create new segments lazily.

However, your second graph is a much more confusing story.  It's saying `capnp.alloc` is taking a very small local time, but a huge cumulative time, and it's a leaf: it no longer calls `Allocate` on the `Arena`.  There are a couple optimizations I can think of, but I don't know what the bottleneck here is.  What platform are you profiling on?  Is this program running inside a VM? (Just trying to rule out potential sources of inaccuracy in the profile graph.)

**Comment by zombiezen** [comment] 2016-08-03 17:07
And actually: can you give me a ballpark idea of how many times `Batch` gets called in this program?  Again, it still seems plausible/fine that the majority of the time in `Batch` is spent on setting stuff in the Cap'n Proto struct.  My benchmarks still show that this operation is fairly fast.

**Comment by zhaoguojie2010** [comment] 2016-08-04 11:07
hello @zombiezen 


1.  I modified my code and use pre-allocated mem using `capnp.SingleSegment(make([]byte, 0, 16<<20))` .(I'm batching 10k Request each time.) Now it's working perfectly. However if i use `capnp.MultiSegment` in the client side and send the capnp message to server, server will always get empty `Request_List` while `Requests.id` and `Requests.count` are both ok. Any idea?


2.  My platform is MacOX, not using any container.

**Comment by zombiezen** [comment] 2016-08-09 16:43
Interesting.  The MultiSegment issue sounds like a bug; I haven't had time yet to create a reproducible test case.  I know that Go has historically had issues accurately profiling on Mac, but I thought that was cleared up on some recent OS version.

**Comment by zombiezen** [comment] 2016-09-04 16:06
Closing this bug out since the performance seems to have been addressed for your application.  If you have a repro case for the `capnp.MultiSegment` issue, please file another bug.  The far pointer code paths are not as well exercised, so if they fail, I would like to know what cases to cover.

**Closed by zombiezen** 2016-09-04 16:06 UTC
Labels: question
