### ISSUE TITLE
internal error with capnpc-go

### ISSUE THREAD

**Issue by dangerousHobo** [zombiezen/go-capnproto2#40] opened 2016-07-15 13:28 UTC
I'm new to using Cap'n Proto with Go. I have a schema file and it compiles fine with C++, `capnp compile  -oc++ serialcom.capnp`

But with go-capnproto2 I get the following error:
```
$ capnp compile -I$GOPATH/src/zombiezen.com/go/capnproto2/std -ogo serialcom.capnp

capnpc-go: generating serialcom.capnp: field SerialCom.databits: internal error (bad schema?): missing import declaration for serialcom.capnp:SerialCom.DataBits
go: plugin failed: exit code 1
```
My serialcom.capnp file:
```
using Go = import "/go.capnp";

@0xe3d3b49ab383156d;
$Go.package("schema");

struct SerialCom {
	enum Parity {
		none @0;
		odd @1;
		even @2;
		mark @3;
		space @4;
	}
	enum Flow {
		none @0;
		xonXoff @1;
		rtsCts @2;
		dsrDtr @3;
	}
	enum DataBits {
		five @0;
		six @1;
		seven @2;
		eight @3;
	}
	enum StopBits {
		one @0;
		ondAndOneHalf @1;
		two @2;
	}
	baud @0 :UInt32;
	databits @1 :DataBits;
	stopbits @2 :StopBits;
	parity @3 :Parity;
	flow @4 :Flow;
}
```

```
$ capnp compile -I$GOPATH/src/zombiezen.com/go/capnproto2/std -ocapnp serialcom.capnp 

# serialcom.capnp
@0xe3d3b49ab383156d;
$import "/go.capnp".package("schema");
struct SerialCom @0xcfcef7366f2a7f37 {  # 16 bytes, 0 ptrs
  baud @0 :UInt32;  # bits[0, 32)
  databits @1 :DataBits;  # bits[32, 48)
  stopbits @2 :StopBits;  # bits[48, 64)
  parity @3 :Parity;  # bits[64, 80)
  flow @4 :Flow;  # bits[80, 96)
  enum Parity @0x9141192533ac9d3c {
    none @0;
    odd @1;
    even @2;
    mark @3;
    space @4;
  }
  enum Flow @0xeb0d81c11a747fd5 {
    none @0;
    xonXoff @1;
    rtsCts @2;
    dsrDtr @3;
  }
  enum DataBits @0xe51c73a9ef981bfc {
    five @0;
    six @1;
    seven @2;
    eight @3;
  }
  enum StopBits @0x85c7d8fddd6bc8fb {
    one @0;
    ondAndOneHalf @1;
    two @2;
  }
}
```

I'm I doing something wrong when compiling from capnp-go?
I'm using go-capnproto2 from Git, built from 98dbe11ec6aa8802e (June 19 10:27:45 2016 ).

**Comment by zombiezen** [comment] 2016-07-15 16:55
dupe of #36

**Closed** 2016-07-15 16:56 UTC
Labels: duplicate

**Comment by dangerousHobo** [comment] 2016-07-15 18:04
To help anyone that comes across this:

I had to add the following to my serialcom.capnp file `$Go.import()` with an import path. After that it worked. The annotations `$Go.package` and $Go.import` are both required, as pointed out in the GoDocs but not on the Getting Started wiki page, which is what brought about my troubles.

**Comment by zombiezen** [comment] 2016-07-15 18:07
Do you think it's worth calling out more?  All the examples on the Getting Started page have both, but I don't want to overwhelm folks that are first starting out.
